---
title: "Exercise 4"
format:
  html:
    self-contained: true
    embed-resources: true
    html-math-method: katex
jupyter: python3
execute:
  keep-ipynb: false
  echo: false
---

::: {.callout-note}
Here's the output for the specs Device and software I'm using with it:
```sh
$ nvidia-smi
Tue Mar 24 15:45:36 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 595.54                 Driver Version: 595.79         CUDA Version: 13.2     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4070 ...    On  |   00000000:01:00.0 Off |                  N/A |
| N/A   39C    P0             16W /  105W |      69MiB /   8188MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
```
:::


## 1. 

### a.

#### Output

See `hello_cuda/cuda_hello.output` for the output from `hello_cuda/cuda_hello.cu` on my machine. This is the maximum that my machine could output at one block.

For `hello_cuda/cuda_hell1.cu` the max output would be too large. With output from $1024$ threads from $864$ blocks. Here's a snippet of the output from the input `./cuda_hello1 200 1024`:
```bash
Hello from thread 306 in block 40
Hello from thread 307 in block 40
Hello from thread 308 in block 40
Hello from thread 309 in block 40
Hello from thread 310 in block 40
Hello from thread 311 in block 40
Hello from thread 312 in block 40
Hello from thread 313 in block 40
Hello from thread 314 in block 40
Hello from thread 315 in block 40
Hello from thread 316 in block 40
Hello from thread 317 in block 40
Hello from thread 318 in block 40
Hello from thread 319 in block 40
Hello from thread 352 in block 38
Hello from thread 353 in block 38
Hello from thread 354 in block 38
Hello from thread 355 in block 38
Hello from thread 356 in block 38
Hello from thread 357 in block 38
Hello from thread 358 in block 38
Hello from thread 359 in block 38
Hello from thread 360 in block 38
Hello from thread 361 in block 38
Hello from thread 362 in block 38
Hello from thread 363 in block 38
Hello from thread 364 in block 38
Hello from thread 365 in block 38
Hello from thread 366 in block 38
Hello from thread 367 in block 38
Hello from thread 368 in block 38
Hello from thread 369 in block 38
Hello from thread 370 in block 38
Hello from thread 371 in block 38
Hello from thread 372 in block 38
Hello from thread 373 in block 38
Hello from thread 374 in block 38
Hello from thread 375 in block 38
Hello from thread 376 in block 38
Hello from thread 377 in block 38
Hello from thread 378 in block 38
Hello from thread 379 in block 38
Hello from thread 380 in block 38
Hello from thread 381 in block 38
Hello from thread 382 in block 38
Hello from thread 383 in block 38
Hello from thread 704 in block 40
Hello from thread 705 in block 40
Hello from thread 706 in block 40
Hello from thread 707 in block 40
Hello from thread 708 in block 40
Hello from thread 709 in block 40
Hello from thread 710 in block 40
Hello from thread 711 in block 40
Hello from thread 712 in block 40
Hello from thread 713 in block 40
Hello from thread 714 in block 40
Hello from thread 715 in block 40
Hello from thread 716 in block 40
Hello from thread 717 in block 40
Hello from thread 718 in block 40
Hello from thread 719 in block 40
Hello from thread 720 in block 40
Hello from thread 721 in block 40
Hello from thread 722 in block 40
Hello from thread 723 in block 40
Hello from thread 724 in block 40
Hello from thread 725 in block 40
Hello from thread 726 in block 40
Hello from thread 727 in block 40
Hello from thread 728 in block 40
Hello from thread 729 in block 40
Hello from thread 730 in block 40
Hello from thread 731 in block 40
Hello from thread 732 in block 40
Hello from thread 733 in block 40
Hello from thread 734 in block 40
Hello from thread 735 in block 40
Hello from thread 768 in block 40
Hello from thread 769 in block 40
Hello from thread 770 in block 40
Hello from thread 771 in block 40
Hello from thread 772 in block 40
Hello from thread 773 in block 40
Hello from thread 774 in block 40
Hello from thread 775 in block 40
Hello from thread 776 in block 40
Hello from thread 777 in block 40
Hello from thread 778 in block 40
Hello from thread 779 in block 40
Hello from thread 780 in block 40
Hello from thread 781 in block 40
Hello from thread 782 in block 40
Hello from thread 783 in block 40
Hello from thread 784 in block 40
Hello from thread 785 in block 40
Hello from thread 786 in block 40
Hello from thread 787 in block 40
Hello from thread 788 in block 40
Hello from thread 789 in block 40
Hello from thread 790 in block 40
Hello from thread 791 in block 40
Hello from thread 792 in block 40
Hello from thread 793 in block 40
Hello from thread 794 in block 40
Hello from thread 795 in block 40
Hello from thread 796 in block 40
Hello from thread 797 in block 40
Hello from thread 798 in block 40
Hello from thread 799 in block 40
Hello from thread 928 in block 40
Hello from thread 929 in block 40
Hello from thread 930 in block 40
Hello from thread 931 in block 40
Hello from thread 932 in block 40
Hello from thread 933 in block 40
Hello from thread 934 in block 40
Hello from thread 935 in block 40
Hello from thread 936 in block 40
Hello from thread 937 in block 40
Hello from thread 938 in block 40
Hello from thread 939 in block 40
Hello from thread 940 in block 40
Hello from thread 941 in block 40
Hello from thread 942 in block 40
Hello from thread 943 in block 40
Hello from thread 944 in block 40
Hello from thread 945 in block 40
Hello from thread 946 in block 40
Hello from thread 947 in block 40
Hello from thread 948 in block 40
Hello from thread 949 in block 40
Hello from thread 950 in block 40
Hello from thread 951 in block 40
Hello from thread 952 in block 40
Hello from thread 953 in block 40
Hello from thread 954 in block 40
Hello from thread 955 in block 40
Hello from thread 956 in block 40
Hello from thread 957 in block 40
Hello from thread 958 in block 40
Hello from thread 959 in block 40
Hello from thread 864 in block 40
Hello from thread 865 in block 40
Hello from thread 866 in block 40
Hello from thread 867 in block 40
Hello from thread 868 in block 40
Hello from thread 869 in block 40
Hello from thread 870 in block 40
Hello from thread 871 in block 40
Hello from thread 872 in block 40
Hello from thread 873 in block 40
Hello from thread 874 in block 40
Hello from thread 875 in block 40
Hello from thread 876 in block 40
Hello from thread 877 in block 40
Hello from thread 878 in block 40
Hello from thread 879 in block 40
Hello from thread 880 in block 40
Hello from thread 881 in block 40
Hello from thread 882 in block 40
Hello from thread 883 in block 40
Hello from thread 884 in block 40
Hello from thread 885 in block 40
Hello from thread 886 in block 40
Hello from thread 887 in block 40
Hello from thread 888 in block 40
Hello from thread 889 in block 40
Hello from thread 890 in block 40
Hello from thread 891 in block 40
Hello from thread 892 in block 40
Hello from thread 893 in block 40
Hello from thread 894 in block 40
Hello from thread 895 in block 40
Hello from thread 864 in block 45
Hello from thread 865 in block 45
Hello from thread 866 in block 45
Hello from thread 867 in block 45
Hello from thread 868 in block 45
Hello from thread 869 in block 45
Hello from thread 870 in block 45
Hello from thread 871 in block 45
Hello from thread 872 in block 45
Hello from thread 873 in block 45
Hello from thread 874 in block 45
Hello from thread 875 in block 45
Hello from thread 876 in block 45
Hello from thread 877 in block 45
Hello from thread 878 in block 45
Hello from thread 879 in block 45
Hello from thread 880 in block 45
Hello from thread 881 in block 45
Hello from thread 882 in block 45
Hello from thread 883 in block 45
Hello from thread 884 in block 45
Hello from thread 885 in block 45
Hello from thread 886 in block 45
Hello from thread 887 in block 45
Hello from thread 888 in block 45
Hello from thread 889 in block 45
Hello from thread 890 in block 45
Hello from thread 891 in block 45
Hello from thread 892 in block 45
Hello from thread 893 in block 45
Hello from thread 894 in block 45
Hello from thread 895 in block 45
Hello from thread 736 in block 45
```


#### Analysis

This continues in a similar form depending on how many blocks you use.

- It looks like for `cuda_hello.cu` the maximum amount of threads that can print is $1024$. Which is the amount of threads that can be on one block for my GPU.
  - For `cuda_hello1.cu` the max amount of threads that can print hello is $864 * 1024$. With $864$ being how many blocks there are on the GPU and $1024$ being how many threads there are on each block.
  - "Can you use bigger blocks and threads"
    - Well, in my case, for my GPU, I would not be able to scale any more than I have. But, if I had access to more hardware, the program would be able to scale by increasing the block size and threads used for each of those blocks up to however many the hardware could provide. Obviously if you're using multiple hosts you would need to also use MPI.

### b. 

#### Output

I built the `cuda_trap1.cu` program and using nearly the maximum available values I could put for `n` and the block count and threads per block, these are my results:

```c
$ ./cuda_trap1 884000 0 3.14159265358979323846264338327950288 864 1024
The area as computed by cuda is: 2.000657e+00
The area as computed by cpu is: 2.000605e+00
Device times:  min = 5.952981e-01, max = 6.454661e-01, avg = 6.299590e-01
  Host times:  min = 3.762007e-03, max = 5.332947e-03, avg = 3.930178e-03
```

#### Comparison

Device speed: `6.299590e-01`

Host speed: `3.930178e-03`

``` {python}
host_trap_speed = 3.930178e-03
device_trap_speed = 6.299590e-01

device_over_host_speed = device_trap_speed / host_trap_speed
```

The device was `{python} device_over_host_speed`x slower than the host.

As you can see, there is not a speedup from using the Device vs. the Host in this case. From what I've researched and based on the book, this is likely due to program architecture; rather than hardware differences. With a better designed CUDA program, the Device should perform quicker than the Host.

#### Correctness

They did get approxemately $2.0$ when $a = 0$ and $b = pi$.

#### Command Line Argument Explanation

- `n`
  - The amount of trapezoids to use
- `a`
  - The start index for the function
- `b`
  - The end index for the function
- `blk_ct`
  - The amount of blocks to be used on the Device
- `th_per_blk`
  - The amount of threads that will be run on each block

#### Program Simplification

Look at `cuda_trap1.cu` and compile it for yourself inputting the amount of trapezoids in as the first and only argument in the command line.

The output should look like this:
```c
$ ./cuda_trap1 1000000
The area as computed by cuda is: 2.000982e+00
The area as computed by cpu is: 2.001454e+00
Device times:  min = 6.419001e-01, max = 7.105761e-01, avg = 6.882100e-01
  Host times:  min = 4.268169e-03, max = 5.291939e-03, avg = 4.500465e-03
```

As you can see, even with the change in arugments required and slight refactor to enable 1 million+ trapezoid processing, the Device is still slower than a single core on the host.

## 2. 

``` {python}
import plotly.graph_objects as go
import csv

def load_single_column_csv(path):
    values = []
    with open(path, newline='') as f:
        for row in csv.reader(f):
            if row:
                values.append(float(row[0]))
    return values

original = load_single_column_csv("functiongen/Ex4-Acceleration-Profile.csv")
interpolated = load_single_column_csv("functiongen/interop-output-10ps.csv")

# Original data is 1 sample/sec: t = 0, 1, 2, ..., 1800
orig_time = [float(i) for i in range(len(original))]

# Interpolated data is 10 samples/sec: t = 0, 0.1, 0.2, ..., 1800
steps_per_sec = (len(interpolated) - 1) // (len(original) - 1)
dt = 1.0 / steps_per_sec
interp_time = [i * dt for i in range(len(interpolated))]

fig = go.Figure()

fig.add_trace(go.Scatter(
    x=interp_time,
    y=interpolated,
    mode='lines',
    name=f'Interpolated ({steps_per_sec} samples/sec)',
    line=dict(color='royalblue', width=10.0),
    opacity=0.85,
))

fig.add_trace(go.Scatter(
    x=orig_time,
    y=original,
    mode='markers',
    name='Original (1 sample/sec)',
    marker=dict(color='red', size=4, symbol='circle'),
))

fig.update_layout(
    title='Acceleration Profile: Interpolated vs Original 1-Second Data',
    xaxis_title='Time (seconds)',
    yaxis_title='Acceleration',
    legend=dict(x=0.5, y=1.1, xanchor='center', yanchor='bottom', orientation='h'),
    hovermode='x unified',
)

fig.show()
```

## 3.

### a.

Refer to `mpi_train.c` to see my implementation. You can use `make` in the `hello_cluster/` directory to compile it and run it with `mpirun`.

This is the output I got with running it with one process at an interpolated $dt=0.001$ seconds per step:
```bash
$ time mpirun -np 1 ./mpi_train
Will divide up work for input table of size = 1801
Went parallel: rank 0 of 1 doing work for 1801 steps
Sum of DefaultProfile for rank 0 of 1 on LAPTOP-O8LRLROT is -0.000000

Rank 0 g_sum = -0.000000

Curr t=0: a=0.000000 for v=0.001451
Curr t=100: a=0.290476 for v=14.814141
Curr t=200: a=0.290476 for v=43.861761
Curr t=300: a=0.290476 for v=72.907930
Curr t=400: a=0.000000 for v=87.142860
Curr t=500: a=0.000000 for v=87.142860
Curr t=600: a=0.000000 for v=87.142860
Curr t=700: a=0.000000 for v=87.142860
Curr t=800: a=0.000000 for v=87.142860
Curr t=900: a=0.000000 for v=87.142860
Curr t=1000: a=0.000000 for v=87.142860
Curr t=1100: a=0.000000 for v=87.142860
Curr t=1200: a=0.000000 for v=87.142860
Curr t=1300: a=0.000000 for v=87.142860
Curr t=1400: a=0.000000 for v=87.141409
Curr t=1500: a=-0.290476 for v=72.328719
Curr t=1600: a=-0.290476 for v=43.281099
Curr t=1700: a=-0.290476 for v=14.234930
Curr t=1800: a=0.000000 for v=-0.000000

Velocity TRACE: Rank 0 sum of default_sum = -0.000000

Rank 0 g_sum = 122000.003272

Curr t=0: a=0.000000 for p=0.003627
Curr t=100: a=0.290476 for p=513.763949
Curr t=200: a=0.290476 for p=3476.592142
Curr t=300: a=0.290476 for p=9344.177983
Curr t=400: a=0.000000 for p=17602.769852
Curr t=500: a=0.000000 for p=26317.055852
Curr t=600: a=0.000000 for p=35031.341852
Curr t=700: a=0.000000 for p=43745.627852
Curr t=800: a=0.000000 for p=52459.913853
Curr t=900: a=0.000000 for p=61174.199853
Curr t=1000: a=0.000000 for p=69888.485852
Curr t=1100: a=0.000000 for p=78602.771852
Curr t=1200: a=0.000000 for p=87317.057851
Curr t=1300: a=0.000000 for p=96031.343850
Curr t=1400: a=0.000000 for p=104745.625498
Curr t=1500: a=-0.290476 for p=112946.151175
Curr t=1600: a=-0.290476 for p=118697.608983
Curr t=1700: a=-0.290476 for p=121544.309142
Curr t=1800: a=0.000000 for p=122000.003272

Position TRACE: Rank 0 sum of default_sum = 122000.003272

real    0m0.332s
user    0m0.061s
sys     0m0.028s
```

#### Report

As you can see the final calculated position was $122000.003272$ meters and the steady state peak velocity was $87.142860$ m/s.

### b.

```bash
$ time mpirun -np 1 ./mpi_train
Will divide up work for input table of size = 1801
Went parallel: rank 0 of 1 doing work for 1801 steps
Sum of DefaultProfile for rank 0 of 1 on LAPTOP-O8LRLROT is -0.000000

Rank 0 g_sum = -0.000000

Curr t=0: a=0.000000 for v=0.001452
Curr t=100: a=0.290476 for v=14.814272
Curr t=200: a=0.290476 for v=43.861892
Curr t=300: a=0.290476 for v=72.908059
Curr t=400: a=0.000000 for v=87.142860
Curr t=500: a=0.000000 for v=87.142860
Curr t=600: a=0.000000 for v=87.142860
Curr t=700: a=0.000000 for v=87.142860
Curr t=800: a=0.000000 for v=87.142860
Curr t=900: a=0.000000 for v=87.142860
Curr t=1000: a=0.000000 for v=87.142860
Curr t=1100: a=0.000000 for v=87.142860
Curr t=1200: a=0.000000 for v=87.142860
Curr t=1300: a=0.000000 for v=87.142860
Curr t=1400: a=0.000000 for v=87.141408
Curr t=1500: a=-0.290476 for v=72.328588
Curr t=1600: a=-0.290476 for v=43.280968
Curr t=1700: a=-0.290476 for v=14.234801
Curr t=1800: a=0.000000 for v=-0.000000

Velocity TRACE: Rank 0 sum of default_sum = -0.000000

Rank 0 g_sum = 122000.003266

Curr t=0: a=0.000000 for p=0.003631
Curr t=100: a=0.290476 for p=513.777542
Curr t=200: a=0.290476 for p=3476.631877
Curr t=300: a=0.290476 for p=9344.243856
Curr t=400: a=0.000000 for p=17602.848279
Curr t=500: a=0.000000 for p=26317.134278
Curr t=600: a=0.000000 for p=35031.420278
Curr t=700: a=0.000000 for p=43745.706277
Curr t=800: a=0.000000 for p=52459.992276
Curr t=900: a=0.000000 for p=61174.278276
Curr t=1000: a=0.000000 for p=69888.564275
Curr t=1100: a=0.000000 for p=78602.850274
Curr t=1200: a=0.000000 for p=87317.136273
Curr t=1300: a=0.000000 for p=96031.422273
Curr t=1400: a=0.000000 for p=104745.703916
Curr t=1500: a=-0.290476 for p=112946.216004
Curr t=1600: a=-0.290476 for p=118697.647668
Curr t=1700: a=-0.290476 for p=121544.321689
Curr t=1800: a=0.000000 for p=122000.003266

Position TRACE: Rank 0 sum of default_sum = 122000.003266

real    0m0.612s
user    0m0.268s
sys     0m0.051s
```

#### Report

The final calculated position was $122000.003266$ meters and the steady state peak velocity was $87.142860$ m/s.

#### Comparison

##### Value Comparison

``` {python}
larger_step_distance = 122000.003272
smaller_step_distance = 122000.003266

compare_step_size_distance = 122000.003272 / 122000.003266
```

When compared, the larger step size's distance was `{python} compare_step_size_distance`x larger than the smaller step size's.

For the steady state peak velocity values, they came amount to be the same at $87.142860$.

##### Run Time comparison

``` {python}
larger_step_runtime = 0.332
smaller_step_runtime = 0.612

compare_step_size_time = smaller_step_runtime / larger_step_runtime
```

The runtime for $dt=0.001$ was `{python} larger_step_runtime` and the runtime for $dt=0.0001$ was `{python} smaller_step_runtime`.

The runtime for $dt=0.0001$ was `{python} compare_step_size_time`x longer than $dt=0.001$.

### c.

#### 2 Proccesses

```bash
$ time mpirun -np 2 ./mpi_train
Will divide up work for input table of size = 1801
Went parallel: rank 0 of 2 doing work for 900 steps
Went parallel: rank 1 of 2 doing work for 900 steps
Sum of DefaultProfile for rank 0 of 2 on LAPTOP-O8LRLROT is 87.142860
Sum of DefaultProfile for rank 1 of 2 on LAPTOP-O8LRLROT is -87.142860

Rank 0 g_sum = -0.000000

Curr t=0: a=0.000000 for v=0.001452
Curr t=100: a=0.290476 for v=14.814272
Curr t=200: a=0.290476 for v=43.861892
Curr t=300: a=0.290476 for v=72.908059
Curr t=400: a=0.000000 for v=87.142860
Curr t=500: a=0.000000 for v=87.142860
Curr t=600: a=0.000000 for v=87.142860
Curr t=700: a=0.000000 for v=87.142860
Curr t=800: a=0.000000 for v=87.142860
Curr t=900: a=0.000000 for v=87.142860
Curr t=1000: a=0.000000 for v=87.142860
Curr t=1100: a=0.000000 for v=87.142860
Curr t=1200: a=0.000000 for v=87.142860
Curr t=1300: a=0.000000 for v=87.142860
Curr t=1400: a=0.000000 for v=87.141408
Curr t=1500: a=-0.290476 for v=72.328588
Curr t=1600: a=-0.290476 for v=43.280968
Curr t=1700: a=-0.290476 for v=14.234801
Curr t=1800: a=0.000000 for v=-0.000000

Velocity TRACE: Rank 0 sum of default_sum = -0.000000

Rank 0 g_sum = 122000.003266

Curr t=0: a=0.000000 for p=0.003631
Curr t=100: a=0.290476 for p=513.777542
Curr t=200: a=0.290476 for p=3476.631877
Curr t=300: a=0.290476 for p=9344.243856
Curr t=400: a=0.000000 for p=17602.848279
Curr t=500: a=0.000000 for p=26317.134278
Curr t=600: a=0.000000 for p=35031.420278
Curr t=700: a=0.000000 for p=43745.706277
Curr t=800: a=0.000000 for p=52459.992276
Curr t=900: a=0.000000 for p=61174.278276
Curr t=1000: a=0.000000 for p=69888.564275
Curr t=1100: a=0.000000 for p=78602.850274
Curr t=1200: a=0.000000 for p=87317.136274
Curr t=1300: a=0.000000 for p=96031.422273
Curr t=1400: a=0.000000 for p=104745.703916
Curr t=1500: a=-0.290476 for p=112946.216004
Curr t=1600: a=-0.290476 for p=118697.647668
Curr t=1700: a=-0.290476 for p=121544.321690
Curr t=1800: a=0.000000 for p=122000.003266

Position TRACE: Rank 0 sum of default_sum = 122000.003266

real    0m0.434s
user    0m0.321s
sys     0m0.027s
```

```{python}
two_proc_completion_time = 0.434
```

#### 4 Proccesses

```bash
$ time mpirun -np 4 ./mpi_train
Went parallel: rank 2 of 4 doing work for 450 steps
Went parallel: rank 3 of 4 doing work for 450 steps
Will divide up work for input table of size = 1801
Went parallel: rank 0 of 4 doing work for 450 steps
Went parallel: rank 1 of 4 doing work for 450 steps
Sum of DefaultProfile for rank 0 of 4 on LAPTOP-O8LRLROT is 87.142860
Sum of DefaultProfile for rank 1 of 4 on LAPTOP-O8LRLROT is 0.000000
Sum of DefaultProfile for rank 2 of 4 on LAPTOP-O8LRLROT is 0.000000
Sum of DefaultProfile for rank 3 of 4 on LAPTOP-O8LRLROT is -87.142860

Rank 0 g_sum = -0.000000

Curr t=0: a=0.000000 for v=0.001452
Curr t=100: a=0.290476 for v=14.814272
Curr t=200: a=0.290476 for v=43.861892
Curr t=300: a=0.290476 for v=72.908059
Curr t=400: a=0.000000 for v=87.142860
Curr t=500: a=0.000000 for v=87.142860
Curr t=600: a=0.000000 for v=87.142860
Curr t=700: a=0.000000 for v=87.142860
Curr t=800: a=0.000000 for v=87.142860
Curr t=900: a=0.000000 for v=87.142860
Curr t=1000: a=0.000000 for v=87.142860
Curr t=1100: a=0.000000 for v=87.142860
Curr t=1200: a=0.000000 for v=87.142860
Curr t=1300: a=0.000000 for v=87.142860
Curr t=1400: a=0.000000 for v=87.141408
Curr t=1500: a=-0.290476 for v=72.328588
Curr t=1600: a=-0.290476 for v=43.280968
Curr t=1700: a=-0.290476 for v=14.234801
Curr t=1800: a=0.000000 for v=-0.000000

Velocity TRACE: Rank 0 sum of default_sum = -0.000000

Rank 0 g_sum = 122000.003266

Curr t=0: a=0.000000 for p=0.003631
Curr t=100: a=0.290476 for p=513.777542
Curr t=200: a=0.290476 for p=3476.631877
Curr t=300: a=0.290476 for p=9344.243856
Curr t=400: a=0.000000 for p=17602.848279
Curr t=500: a=0.000000 for p=26317.134279
Curr t=600: a=0.000000 for p=35031.420278
Curr t=700: a=0.000000 for p=43745.706277
Curr t=800: a=0.000000 for p=52459.992276
Curr t=900: a=0.000000 for p=61174.278276
Curr t=1000: a=0.000000 for p=69888.564275
Curr t=1100: a=0.000000 for p=78602.850275
Curr t=1200: a=0.000000 for p=87317.136274
Curr t=1300: a=0.000000 for p=96031.422273
Curr t=1400: a=0.000000 for p=104745.703916
Curr t=1500: a=-0.290476 for p=112946.216004
Curr t=1600: a=-0.290476 for p=118697.647669
Curr t=1700: a=-0.290476 for p=121544.321690
Curr t=1800: a=0.000000 for p=122000.003266

Position TRACE: Rank 0 sum of default_sum = 122000.003266

real    0m0.386s
user    0m0.329s
sys     0m0.066s
```

```{python}
four_proc_completion_time = 0.386
```

#### 8 Proccesses

```bash
$ time mpirun -np 8 ./mpi_train
Went parallel: rank 6 of 8 doing work for 225 steps
Went parallel: rank 7 of 8 doing work for 225 steps
Will divide up work for input table of size = 1801
Went parallel: rank 0 of 8 doing work for 225 steps
Went parallel: rank 1 of 8 doing work for 225 steps
Went parallel: rank 2 of 8 doing work for 225 steps
Went parallel: rank 3 of 8 doing work for 225 steps
Went parallel: rank 4 of 8 doing work for 225 steps
Went parallel: rank 5 of 8 doing work for 225 steps
Sum of DefaultProfile for rank 0 of 8 on LAPTOP-O8LRLROT is 50.833320
Sum of DefaultProfile for rank 1 of 8 on LAPTOP-O8LRLROT is 36.309540
Sum of DefaultProfile for rank 2 of 8 on LAPTOP-O8LRLROT is 0.000000
Sum of DefaultProfile for rank 3 of 8 on LAPTOP-O8LRLROT is 0.000000
Sum of DefaultProfile for rank 4 of 8 on LAPTOP-O8LRLROT is 0.000000
Sum of DefaultProfile for rank 5 of 8 on LAPTOP-O8LRLROT is 0.000000
Sum of DefaultProfile for rank 6 of 8 on LAPTOP-O8LRLROT is -36.309510
Sum of DefaultProfile for rank 7 of 8 on LAPTOP-O8LRLROT is -50.833350

Rank 0 g_sum = -0.000000

Curr t=0: a=0.000000 for v=0.001452
Curr t=100: a=0.290476 for v=14.814272
Curr t=200: a=0.290476 for v=43.861892
Curr t=300: a=0.290476 for v=72.908059
Curr t=400: a=0.000000 for v=87.142860
Curr t=500: a=0.000000 for v=87.142860
Curr t=600: a=0.000000 for v=87.142860
Curr t=700: a=0.000000 for v=87.142860
Curr t=800: a=0.000000 for v=87.142860
Curr t=900: a=0.000000 for v=87.142860
Curr t=1000: a=0.000000 for v=87.142860
Curr t=1100: a=0.000000 for v=87.142860
Curr t=1200: a=0.000000 for v=87.142860
Curr t=1300: a=0.000000 for v=87.142860
Curr t=1400: a=0.000000 for v=87.141408
Curr t=1500: a=-0.290476 for v=72.328588
Curr t=1600: a=-0.290476 for v=43.280968
Curr t=1700: a=-0.290476 for v=14.234801
Curr t=1800: a=0.000000 for v=-0.000000

Velocity TRACE: Rank 0 sum of default_sum = -0.000000

Rank 0 g_sum = 122000.003269

Curr t=0: a=0.000000 for p=0.003631
Curr t=100: a=0.290476 for p=513.777542
Curr t=200: a=0.290476 for p=3476.631877
Curr t=300: a=0.290476 for p=9344.243856
Curr t=400: a=0.000000 for p=17602.848279
Curr t=500: a=0.000000 for p=26317.134279
Curr t=600: a=0.000000 for p=35031.420278
Curr t=700: a=0.000000 for p=43745.706278
Curr t=800: a=0.000000 for p=52459.992278
Curr t=900: a=0.000000 for p=61174.278277
Curr t=1000: a=0.000000 for p=69888.564277
Curr t=1100: a=0.000000 for p=78602.850276
Curr t=1200: a=0.000000 for p=87317.136276
Curr t=1300: a=0.000000 for p=96031.422275
Curr t=1400: a=0.000000 for p=104745.703918
Curr t=1500: a=-0.290476 for p=112946.216007
Curr t=1600: a=-0.290476 for p=118697.647671
Curr t=1700: a=-0.290476 for p=121544.321692
Curr t=1800: a=0.000000 for p=122000.003269

Position TRACE: Rank 0 sum of default_sum = 122000.003269

real    0m0.375s
user    0m0.588s
sys     0m0.157s
```

```{python}
eight_proc_completion_time = 0.375
```

#### 16 Proccesses

```bash
$ time mpirun -np 16 --use-hwthread-cpus ./mpi_train
Went parallel: rank 8 of 16 doing work for 112 steps
Went parallel: rank 10 of 16 doing work for 112 steps
Went parallel: rank 12 of 16 doing work for 112 steps
Went parallel: rank 15 of 16 doing work for 112 steps
Went parallel: rank 5 of 16 doing work for 112 steps
Went parallel: rank 7 of 16 doing work for 112 steps
Went parallel: rank 1 of 16 doing work for 112 steps
Went parallel: rank 2 of 16 doing work for 112 steps
Went parallel: rank 9 of 16 doing work for 112 steps
Went parallel: rank 11 of 16 doing work for 112 steps
Went parallel: rank 13 of 16 doing work for 112 steps
Went parallel: rank 14 of 16 doing work for 112 steps
Will divide up work for input table of size = 1801
Went parallel: rank 0 of 16 doing work for 112 steps
Went parallel: rank 4 of 16 doing work for 112 steps
Went parallel: rank 3 of 16 doing work for 112 steps
Went parallel: rank 6 of 16 doing work for 112 steps
Sum of DefaultProfile for rank 0 of 16 on LAPTOP-O8LRLROT is 18.009510
Sum of DefaultProfile for rank 1 of 16 on LAPTOP-O8LRLROT is 32.533334
Sum of DefaultProfile for rank 2 of 16 on LAPTOP-O8LRLROT is 30.651054
Sum of DefaultProfile for rank 3 of 16 on LAPTOP-O8LRLROT is 5.948962
Sum of DefaultProfile for rank 4 of 16 on LAPTOP-O8LRLROT is 0.000000
Sum of DefaultProfile for rank 5 of 16 on LAPTOP-O8LRLROT is 0.000000
Sum of DefaultProfile for rank 6 of 16 on LAPTOP-O8LRLROT is 0.000000
Sum of DefaultProfile for rank 7 of 16 on LAPTOP-O8LRLROT is 0.000000
Sum of DefaultProfile for rank 8 of 16 on LAPTOP-O8LRLROT is 0.000000
Sum of DefaultProfile for rank 9 of 16 on LAPTOP-O8LRLROT is 0.000000
Sum of DefaultProfile for rank 10 of 16 on LAPTOP-O8LRLROT is 0.000000
Sum of DefaultProfile for rank 11 of 16 on LAPTOP-O8LRLROT is 0.000000
Sum of DefaultProfile for rank 12 of 16 on LAPTOP-O8LRLROT is -4.554659
Sum of DefaultProfile for rank 13 of 16 on LAPTOP-O8LRLROT is -29.721518
Sum of DefaultProfile for rank 14 of 16 on LAPTOP-O8LRLROT is -32.533334
Sum of DefaultProfile for rank 15 of 16 on LAPTOP-O8LRLROT is -20.240395

Rank 0 g_sum = 0.092954

Curr t=0: a=0.000000 for v=0.001452
Curr t=100: a=0.290476 for v=14.814272
Curr t=200: a=0.290476 for v=43.861892
Curr t=300: a=0.290476 for v=72.908059
Curr t=400: a=0.000000 for v=87.142860
Curr t=500: a=0.000000 for v=87.142860
Curr t=600: a=0.000000 for v=87.142860
Curr t=700: a=0.000000 for v=87.142860
Curr t=800: a=0.000000 for v=87.142860
Curr t=900: a=0.000000 for v=87.142860
Curr t=1000: a=0.000000 for v=87.142860
Curr t=1100: a=0.000000 for v=87.142860
Curr t=1200: a=0.000000 for v=87.142860
Curr t=1300: a=0.000000 for v=87.142860
Curr t=1400: a=0.000000 for v=87.141408
Curr t=1500: a=-0.290476 for v=72.328588
Curr t=1600: a=-0.290476 for v=43.280968
Curr t=1700: a=-0.290476 for v=14.234801
Curr t=1800: a=0.000000 for v=0.000000

Velocity TRACE: Rank 0 sum of default_sum = 0.092954

Rank 0 g_sum = 121999.799937

Curr t=0: a=0.000000 for p=0.003631
Curr t=100: a=0.290476 for p=513.777542
Curr t=200: a=0.290476 for p=3476.631877
Curr t=300: a=0.290476 for p=9344.243856
Curr t=400: a=0.000000 for p=17602.848280
Curr t=500: a=0.000000 for p=26317.134280
Curr t=600: a=0.000000 for p=35031.420280
Curr t=700: a=0.000000 for p=43745.706280
Curr t=800: a=0.000000 for p=52459.992280
Curr t=900: a=0.000000 for p=61174.278280
Curr t=1000: a=0.000000 for p=69888.564280
Curr t=1100: a=0.000000 for p=78602.850280
Curr t=1200: a=0.000000 for p=87317.136280
Curr t=1300: a=0.000000 for p=96031.422280
Curr t=1400: a=0.000000 for p=104745.703923
Curr t=1500: a=-0.290476 for p=112946.216012
Curr t=1600: a=-0.290476 for p=118697.647676
Curr t=1700: a=-0.290476 for p=121544.321698
Curr t=1800: a=0.000000 for p=0.000000

Position TRACE: Rank 0 sum of default_sum = 121999.799937

real    0m0.362s
user    0m0.796s
sys     0m0.290s
```

```{python}
sixteen_proc_completion_time = 0.362
```

In this instance, `--use-hwthread-cpus` allows me to segment the CPU as hardware threads instead of cores. Which enables me to utilize each thread as if it where its own core.

#### Completion Time vs Number of Processes (dt=0.0001)

```{python}
import plotly.graph_objects as go

num_procs = [1, 2, 4, 8, 16]
completion_times = [
    smaller_step_runtime,       # 1 process (sequential dt=0.0001)
    two_proc_completion_time,   # 2 processes
    four_proc_completion_time,  # 4 processes
    eight_proc_completion_time, # 8 processes
    sixteen_proc_completion_time # 16 processes
]

fig = go.Figure()

fig.add_trace(go.Scatter(
    x=num_procs,
    y=completion_times,
    mode='lines+markers',
    name='Wall-clock time',
    line=dict(color='royalblue', width=2),
    marker=dict(size=10, symbol='circle'),
))

fig.update_layout(
    title='MPI Scaling: Completion Time vs Number of Processes (dt=0.0001)',
    xaxis=dict(
        title='Number of MPI Processes',
        tickmode='array',
        tickvals=num_procs,
    ),
    yaxis_title='Completion Time (seconds)',
    hovermode='x unified',
)

fig.show()
```

